services:
  web:
    build: .
    container_name: luizalabs-backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PORT: 8000
      DATABASE_URL: "mongodb://dev:pass123@db:27017/luizalabsdb?directConnection=true"
    networks:
      - appnet

  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: luizalabsdb
      INIT_WAIT_SEC: 3
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
